services:
  - type: web
    name: AI-Product-Recommendation-System
    env: python
    repo: https://github.com/bhuvaneshgowda/AI-Product-Recommendation-System
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_DEBUG
        value: "false"
      - key: SERPAPI_KEY
        fromSecret: SERPAPI_KEY
